### ISSUE TITLE
Using the given Distribution Profiles in the corpusData Folder.

### ISSUE THREAD

**Issue by JakobHoffmann** [se-passau/thor-avm#10]
In the current version it is not possible to use the given Distribution Profiles in the corpusData Folder.
The CreateDistFromFile Method in the file Commander.cs:480 does not parse the files correctly/only accepts files that contain no other symbols than the number. As the used .txt files in the corpusData Folder as well as the files Thor is using internaly are in the format "[number1, number2]" this needs to be added:

srVal.Replace("[", string.Empty).Replace("]", string.Empty).Replace(",", string.Empty)

**Comment by MarcelHimmelreich** [comment]
Sorry for the late reply, it should now work.
