### ISSUE TITLE
unable to start png() device

### ISSUE THREAD

**Issue by pooyanjamshidi** [se-passau/thor-avm#8]
In the feature distribution step, when selecting the target feature distribution, I run into the following exception, which I think is related to R plotting the graphs. I do not see the exception after continuing and going to the next step and then trying again. I put the exception text here. Note that I'm running it on a Windows VM on my Mac, so might be related to slash/backslash mismatch in directory referencing?

************** Exception Text **************
RDotNet.EvaluationException: Error in grDevices::png(..., res = dpi, units = "in") : 
  unable to start png() device

   at RDotNet.REngine.Parse(String statement, StringBuilder incompleteStatement)
   at RDotNet.REngine.<Defer>d__0.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at RDotNet.REngine.Evaluate(String statement)
   at InteracGenerator.RIntegrator.PlotValues(String name, String imagepath, Double adjust, DistributionType type) in \\vmware-host\Shared Folders\Downloads\thor-avm-master\Thor\InteracGenerator\Helper\RIntegrator.cs:line 281
   at InteracGenerator.RIntegrator.PlotValues(Distribution dist, Double adjust) in \\vmware-host\Shared Folders\Downloads\thor-avm-master\Thor\InteracGenerator\Helper\RIntegrator.cs:line 129
   at InteracGenerator.DistStore.set_SelectedFeatureDistribution(Distribution value) in \\vmware-host\Shared Folders\Downloads\thor-avm-master\Thor\InteracGenerator\Helper\DistStore.cs:line 24
   at IntergenDesktop.UserControls.Features.SelectFirst_Click(Object sender, EventArgs e) in \\vmware-host\Shared Folders\Downloads\thor-avm-master\Thor\IntergenDesktop\UserControls\Features.cs:line 222
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
IntergenDesktop
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/IntergenDesktop.exe
----------------------------------------
InteracGenerator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/InteracGenerator.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
RDotNet
    Assembly Version: 1.6.5.0
    Win32 Version: 1.6.5
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/RDotNet.DLL
----------------------------------------
DynamicInterop
    Assembly Version: 0.7.4.0
    Win32 Version: 0.7.4.0
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/DynamicInterop.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
RDotNet.NativeLibrary
    Assembly Version: 1.6.5.0
    Win32 Version: 1.6.5
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/RDotNet.NativeLibrary.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SPLConqueror_Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/SPLConqueror_Core.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Accord.Statistics
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0.5591
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/Accord.Statistics.DLL
----------------------------------------
Accord.Math
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.5706
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/Accord.Math.DLL
----------------------------------------
Accord
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.5706
    CodeBase: file://vmware-host/Shared%20Folders/Downloads/thor-avm-master/Thor/IntergenDesktop/bin/Debug/Accord.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MarcelHimmelreich** [comment]
Error should not occure anymore
